import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import Search from '../components/Search';
import Profile from '../components/Profile';
import Cards from '../components/Cards';
import Analytics from '../components/Analytics';
import Developer from '../components/Developer';
export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/images/favicon.ico" />
      </Head>

      <div className=
      'w-96 h mx-auto shadow-xl p-4 md:w-11/12 rounded-xl'
      >
          <header className='flex '>
            <Sidebar/>
            <Search/>
            <Profile/>
          </header>
          <main className='mt-5'>
            <div className='flex justify-center'>
              <Cards/>
            </div>
            <div className='ml-20 mt-5'>
            <h4 className='font-bold'>Analytics</h4>
            </div>
            <div>
              <Analytics/>
            </div>
          </main>
          <footer className='flex justify-center mt-5'>
            <Developer/>
          </footer>
      </div>

    </>
  )
}
